# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zHLTcL7ah_GL0Ute6fEz4oe0MKDouWtX
"""

"""
Пайплайн автоматической разметки ассоциативных пар.

Данный скрипт демонстрирует полный процесс, от создания признаков до гибридной
правило‑нейросетевой разметки. Эталонная выборка (золотой стандарт) не включена
в репозиторий, поэтому шаг обучения модели BERT будет пропущен, если файл с золотом
не найден.

Для воспроизведения обучения и инференса необходимо, чтобы в рабочем каталоге
находился файл `ML_золото_для обучения.xlsx` (или измените путь в переменной
GOLD_DATA_FILE).
"""

import os
import re
import numpy as np
import pandas as pd
from tqdm.auto import tqdm
import joblib
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, f1_score
from sklearn.preprocessing import StandardScaler
from transformers import AutoModel, AutoTokenizer, Trainer, TrainingArguments
from transformers.modeling_outputs import SequenceClassifierOutput

# КОНФИГУРАЦИЯ
BASE_DIR = "."
EIGHT_WORDS_FILE = os.path.join(BASE_DIR, "0_final_dataset.csv")
GOLD_DATA_FILE   = os.path.join(BASE_DIR, "ML_золото_для обучения.xlsx")
FULL_DATASET_FILE = os.path.join(BASE_DIR, "датасет_для ML_итог.xlsx")
FINAL_OUTPUT = os.path.join(BASE_DIR, "0_final_dataset.csv")
MODEL_SAVE_DIR = "./final_trained_model_gold"
SCALER_SAVE_PATH = "feature_scaler.pkl"
BERT_MODEL_NAME = "sberbank-ai/ruBert-base"
RANDOM_STATE = 42
BATCH_SIZE = 64

# 0. ПОДГОТОВКА ПРИЗНАКОВ И ЦЕЛЕВЫХ МЕТОК
def load_and_featurize(path):

    if not os.path.exists(path):
        raise FileNotFoundError(f"Файл {path} не найден. Пожалуйста, поместите его в рабочую директорию.")
    df = pd.read_excel(path)
    df_ML = pd.DataFrame()
    df_ML['стимул'] = df['стимул']
    df_ML['ассоциация'] = df['ассоциация']

    # Количество слов в ассоциации
    df_ML['assoc_word_count'] = df['ассоциация'].astype(str).apply(lambda x: len(x.strip().split()))

    # Числовые признаки
    cols_to_fix = ['Wu Palmer', 'Delta P', 'Dice Score', 'PMI', 'частота', 'Концептуальная частота']
    for col in cols_to_fix:
        df_ML[col] = pd.to_numeric(df.get(col, 0), errors='coerce').fillna(0)

    # Формальные и эпидигматические признаки
    epi_col = df['эпидигматика и формальная связь'].astype(str).str.lower()
    df_ML['feat_identical'] = epi_col.apply(lambda x: 1 if 'идентичные' in x else 0)
    df_ML['feat_formal_phonetic'] = epi_col.apply(lambda x: 1 if any(kw in x for kw in ['фонетическая', 'графическая', 'историческая']) else 0)
    df_ML['feat_epidigmatic'] = epi_col.apply(lambda x: 1 if 'эпидигматическая' in x else 0)
    df_ML['feat_grammatical_forms'] = epi_col.apply(lambda x: 1 if 'грамматическая' in x else 0)

    # Парадигматика (RuWordNet)
    para_col = df['RuWordNet'].astype(str).str.lower()
    df_ML['para_synonym'] = para_col.apply(lambda x: 1 if 'синоним' in x else 0)
    df_ML['para_antonym'] = para_col.apply(lambda x: 1 if 'антоним' in x else 0)
    df_ML['para_hippo'] = para_col.apply(lambda x: 1 if 'гипоним' in x or 'гипероним' in x else 0)
    df_ML['para_any'] = para_col.apply(lambda x: 1 if any(c.isalpha() for c in x) and x != 'nan' else 0)

    # Совпадение частей речи
    def check_pos_match(s_pos, a_pos):
        s_str, a_str = str(s_pos).strip(), str(a_pos).strip()
        if '+' in a_str: return 0
        s_first = s_str.split('/')[0]
        a_first = a_str.split('/')[0]
        s_clean = re.sub(r'[^\w]', '', s_first).upper()
        a_clean = re.sub(r'[^\w]', '', a_first).upper()
        return 1 if (s_clean == a_clean and s_clean != '') else 0
    df_ML['POS_match'] = df.apply(lambda row: check_pos_match(row['часть речи стимула'], row['часть речи ассоциации']), axis=1)

    # Семантическая группа и фрейм
    df_ML['sem_tag'] = df['общая сем.группа'].apply(lambda x: 1 if pd.notna(x) and str(x).strip() != '' else 0)
    fb_cols = ['FB_точные примеры', 'FB_пересечение', 'FB_ролевая связь']
    df_ML['frame_tag'] = df[fb_cols].apply(
        lambda row: 1 if any(pd.notna(x) and str(x).strip() != '' for x in row) else 0, axis=1
    )

    # Синтаксический признак (объединённый)
    syntax_list = [
        'атрибутивное: определительное', 'актантное', 'атрибутивное: обстоятельственное',
        'атрибутивное', 'атрибутивное: аппроксимативно-порядковое/количественное', 'служебное'
    ]
    df_ML['synt'] = df['Синтаксическая разметка'].astype(str).apply(
        lambda x: 1 if any(syn in x for syn in syntax_list) else 0
    )

    # Устойчивость (коллокация)
    df_ML['collocation'] = df['устойчивость'].astype(str).str.lower().apply(lambda x: 1 if 'коллокация' in x else 0)

    # Multi-label цели (типы связи)
    target_list = [
        'синтаксический', 'синтагматический', 'эпидигматический',
        'парадигматический', 'коллокативный', 'тематический',
        'составная', 'идентичные', 'формальный', 'грамматический (формы слова)',
        'не определена'
    ]
    target_column = 'тип связи'
    for t in target_list:
        clean_name = t.replace(' (формы слова)', '').replace(' ', '_')
        safe_col_name = f"target_{clean_name}"
        df_ML[safe_col_name] = df[target_column].astype(str).apply(
            lambda x: 1 if t.lower() in [tag.strip().lower() for tag in x.split('/')] else 0
        )
    return df_ML

print("Шаг 1: Генерация признаков")
df_ML = load_and_featurize(EIGHT_WORDS_FILE)

# 1. РАСЧЁТ S-BERT (требуется интернет)
print("Шаг 2: Расчёт S-BERT")
try:
    from sentence_transformers import SentenceTransformer
    from sklearn.metrics.pairwise import cosine_similarity
    sbert_model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')
    stims = df_ML['стимул'].astype(str).tolist()
    assocs = df_ML['ассоциация'].astype(str).tolist()
    stim_embs = sbert_model.encode(stims, show_progress_bar=True, batch_size=32)
    assoc_embs = sbert_model.encode(assocs, show_progress_bar=True, batch_size=32)
    sims = [cosine_similarity(s.reshape(1, -1), a.reshape(1, -1))[0][0] for s, a in zip(stim_embs, assoc_embs)]
    df_ML['sim_sbert'] = sims
    print("S-BERT рассчитан.")
except ImportError:
    print("sentence_transformers не установлен. sim_sbert будет заполнен нулями.")
    df_ML['sim_sbert'] = 0.0

df_ML.to_excel(FULL_DATASET_FILE, index=False)
print(f"Промежуточный датасет сохранён в {FULL_DATASET_FILE}")

# 2. ОБУЧЕНИЕ МОДЕЛИ BERT (если есть золотой стандарт)
feature_cols = [
    'feat_identical', 'feat_formal_phonetic', 'feat_epidigmatic', 'feat_grammatical_forms',
    'POS_match', 'para_synonym', 'para_antonym', 'para_hippo', 'para_any',
    'sem_tag', 'frame_tag', 'synt', 'collocation', 'Wu Palmer', 'sim_sbert'
]

if os.path.exists(GOLD_DATA_FILE):
    print("Шаг 3: Обучение модели BERT")
    gold_source_df = pd.read_excel(GOLD_DATA_FILE)
    gold_source_df = gold_source_df.dropna(subset=['стимул', 'ассоциация'])

    target_cols = [col for col in df_ML.columns if col.startswith('target_')]
    class_names = [col.replace('target_', '') for col in target_cols]

    # Проверка наличия признаков
    missing_feat = [f for f in feature_cols if f not in gold_source_df.columns]
    if missing_feat:
        raise KeyError(f"В эталонном файле отсутствуют признаки: {missing_feat}")

    train_df, val_df = train_test_split(gold_source_df, test_size=0.2, random_state=RANDOM_STATE)
    train_labels = train_df[target_cols].values.astype(np.float32)
    val_labels   = val_df[target_cols].values.astype(np.float32)

    scaler = StandardScaler()
    train_feat = scaler.fit_transform(train_df[feature_cols].values.astype(np.float32))
    val_feat   = scaler.transform(val_df[feature_cols].values.astype(np.float32))
    joblib.dump(scaler, SCALER_SAVE_PATH)

    tokenizer = AutoTokenizer.from_pretrained(BERT_MODEL_NAME)
    train_enc = tokenizer(train_df['стимул'].tolist(), train_df['ассоциация'].tolist(),
                          truncation=True, padding=True, max_length=64, return_tensors='pt')
    val_enc   = tokenizer(val_df['стимул'].tolist(), val_df['ассоциация'].tolist(),
                          truncation=True, padding=True, max_length=64, return_tensors='pt')

    class HybridDataset(torch.utils.data.Dataset):
        def __init__(self, encodings, features, labels):
            self.encodings = encodings
            self.features = features
            self.labels = labels
        def __getitem__(self, idx):
            item = {key: val[idx] for key, val in self.encodings.items()}
            item['features'] = torch.tensor(self.features[idx], dtype=torch.float)
            item['labels'] = torch.tensor(self.labels[idx], dtype=torch.float)
            return item
        def __len__(self):
            return len(self.labels)

    train_dataset = HybridDataset(train_enc, train_feat, train_labels)
    val_dataset   = HybridDataset(val_enc, val_feat, val_labels)

    class FocalLoss(nn.Module):
        def __init__(self, alpha=0.25, gamma=2.0):
            super().__init__()
            self.alpha, self.gamma = alpha, gamma
        def forward(self, inputs, targets):
            bce = nn.functional.binary_cross_entropy_with_logits(inputs, targets, reduction='none')
            pt = torch.exp(-bce)
            return (self.alpha * (1 - pt) ** self.gamma * bce).mean()

    class BertHybrid(nn.Module):
        def __init__(self, model_name, num_labels, num_features):
            super().__init__()
            self.bert = AutoModel.from_pretrained(model_name)
            self.dropout = nn.Dropout(0.4)
            self.classifier = nn.Linear(768 + num_features, num_labels)
            self.loss_fn = FocalLoss(0.25, 2.0)
        def forward(self, input_ids, attention_mask, features, labels=None, **kwargs):
            outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
            pooled = self.dropout(outputs.pooler_output)
            combined = torch.cat((pooled, features), dim=1)
            logits = self.classifier(combined)
            loss = self.loss_fn(logits, labels) if labels is not None else None
            return SequenceClassifierOutput(loss=loss, logits=logits)

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = BertHybrid(BERT_MODEL_NAME, len(target_cols), len(feature_cols))
    model.to(device)
    for param in model.parameters():
        param.data = param.data.contiguous()

    training_args = TrainingArguments(
        output_dir='./results',
        num_train_epochs=10,
        per_device_train_batch_size=8,
        per_device_eval_batch_size=16,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="f1_macro",
        learning_rate=2e-5,
        weight_decay=0.05,
        logging_steps=10,
        report_to="none"
    )

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        probs = torch.sigmoid(torch.tensor(logits)).numpy()
        preds = (probs >= 0.5).astype(int)
        return {'f1_macro': f1_score(labels, preds, average='macro', zero_division=0)}

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        compute_metrics=compute_metrics
    )
    trainer.train()
    trainer.save_model(MODEL_SAVE_DIR)
    tokenizer.save_pretrained(MODEL_SAVE_DIR)
    torch.save(model.state_dict(), os.path.join(MODEL_SAVE_DIR, "pytorch_model_weights.bin"))

    # Оценка на валидации
    preds = trainer.predict(val_dataset)
    probs = torch.sigmoid(torch.tensor(preds.predictions)).numpy()
    y_pred = (probs >= 0.5).astype(int)
    print("\n=== Результаты на валидации ===")
    print(classification_report(val_labels, y_pred, target_names=class_names, zero_division=0))

    # Сохраняем обученную модель и scaler
    print(f"Модель сохранена в {MODEL_SAVE_DIR}")
else:
    print(" Шаг 3: Обучение модели ПРОПУЩЕНО (нет золотого стандарта)")
    target_cols = [col for col in df_ML.columns if col.startswith('target_')]
    class_names = [col.replace('target_', '') for col in target_cols]
    tokenizer = None
    scaler = None
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# 3. РАЗМЕТКА НА ПОЛНОМ ДАТАСЕТЕ (если модель обучена)
print("=== Шаг 4: Разметка на полном датасете и гибридная разметка ===")
df_full = pd.read_excel(FULL_DATASET_FILE)

if os.path.exists(GOLD_DATA_FILE) and os.path.exists(MODEL_SAVE_DIR):
    # модель и токенайзер
    tokenizer = AutoTokenizer.from_pretrained(MODEL_SAVE_DIR)
    scaler = joblib.load(SCALER_SAVE_PATH)
    model = BertHybrid(BERT_MODEL_NAME, len(target_cols), len(feature_cols))
    model.load_state_dict(torch.load(os.path.join(MODEL_SAVE_DIR, "pytorch_model_weights.bin"), map_location=device), strict=False)
    model.to(device)
    model.eval()

    # Эталонные строки
    df_gold = pd.read_excel(GOLD_DATA_FILE)
    df_gold['key'] = df_gold['стимул'].astype(str) + '::' + df_gold['ассоциация'].astype(str)
    df_full['key'] = df_full['стимул'].astype(str) + '::' + df_full['ассоциация'].astype(str)
    gold_keys = set(df_gold['key'])
    mask_gold = df_full['key'].isin(gold_keys)
    df_gold_in_full = df_full[mask_gold].copy()
    df_to_predict = df_full[~mask_gold].copy()
    print(f"Строк с эталоном: {len(df_gold_in_full)}, для предсказания: {len(df_to_predict)}")

    X_feat = scaler.transform(df_to_predict[feature_cols].values.astype(np.float32))
    all_probs = []
    with torch.no_grad():
        for i in tqdm(range(0, len(df_to_predict), BATCH_SIZE)):
            batch = df_to_predict.iloc[i:i+BATCH_SIZE]
            batch_feat = torch.tensor(X_feat[i:i+BATCH_SIZE], dtype=torch.float).to(device)
            enc = tokenizer(batch['стимул'].tolist(), batch['ассоциация'].tolist(),
                            truncation=True, padding=True, max_length=64, return_tensors='pt').to(device)
            logits = model(**enc, features=batch_feat).logits
            probs = torch.sigmoid(logits).cpu().numpy()
            all_probs.append(probs)

    probs_array = np.vstack(all_probs)
    y_pred_bert = (probs_array >= 0.5).astype(int)

    def labels_to_str(multi_hot, names):
        tags = [names[i] for i, v in enumerate(multi_hot) if v == 1]
        return ' / '.join(tags) if tags else 'не определена'

    df_to_predict['predicted_labels_final'] = [labels_to_str(row, class_names) for row in y_pred_bert]
    df_to_predict['max_confidence'] = probs_array.max(axis=1)

    # Эталонные строки с их оригинальными метками
    def gold_labels(row):
        vals = [row.get(col, 0) for col in target_cols]
        tags = [class_names[i] for i, v in enumerate(vals) if v == 1]
        return ' / '.join(tags) if tags else 'не определена'
    df_gold_in_full['predicted_labels_final'] = df_gold_in_full.apply(gold_labels, axis=1)
    df_gold_in_full['max_confidence'] = 1.0

    df_combined = pd.concat([df_gold_in_full, df_to_predict], ignore_index=True)
    df_combined.drop(columns=['key'], errors='ignore', inplace=True)
else:
    # Если модели нет
    print("Модель отсутствует. Для демонстрации используются только автоматические правила.")
    df_combined = df_full.copy()
    df_combined['predicted_labels_final'] = 'не определена'
    df_combined['max_confidence'] = 0.0

# 4. ГИБРИДНАЯ ПОСТОБРАБОТКА
print("Шаг 5: Гибридная постобработка")

def auto_labels(row):
    vals = [row.get(col, 0) for col in target_cols]
    tags = [class_names[i] for i, v in enumerate(vals) if v == 1]
    return ' / '.join(tags) if tags else 'не определена'

df_combined['auto_labels_final'] = df_combined.apply(auto_labels, axis=1)

def hybrid_label(row):
    auto_str = str(row.get('auto_labels_final', '')).strip()
    bert_str = str(row.get('predicted_labels_final', '')).strip()

    if auto_str and auto_str != 'не определена':
        auto_tags = [t.strip() for t in auto_str.split('/')]
    else:
        auto_tags = []
    if bert_str and bert_str != 'не определена':
        bert_tags = [t.strip() for t in bert_str.split('/')]
    else:
        bert_tags = []

    if not bert_tags:
        return ' / '.join(sorted(auto_tags)) if auto_tags else 'не определена'

    tags = set(bert_tags)

    # 1. Удаляем идентичные, формальные, эпидигматические, грамматические
    tags.discard('идентичные')
    tags.discard('формальный')
    tags.discard('эпидигматический')
    tags.discard('грамматический')

    # 2. Парадигматика только при совпадении частей речи
    pos_match = row.get('POS_match', 0)
    if 'парадигматический' in tags and pos_match == 0:
        tags.discard('парадигматический')

    # 3. Коллокативный без синтаксического/синтагматического
    if 'коллокативный' in tags and 'синтаксический' not in tags and 'синтагматический' not in tags:
        if pos_match == 0:
            tags.add('синтагматический')
        else:
            tags.add('синтаксический')

    # 4. Исправление синтаксический/синтагматический по POS_match
    if pos_match == 1:
        if 'синтагматический' in tags:
            tags.discard('синтагматический')
            tags.add('синтаксический')
    else:
        if 'синтаксический' in tags:
            tags.discard('синтаксический')
            tags.add('синтагматический')

    # 5. Тематический + второй тег из авто-разметки
    if 'тематический' in tags:
        auto_set = set(auto_tags)
        if 'синтагматический' in auto_set and 'синтагматический' not in tags:
            tags.add('синтагматический')
        if 'синтаксический' in auto_set and 'синтаксический' not in tags:
            tags.add('синтаксический')
        if 'коллокативный' in auto_set and 'коллокативный' not in tags:
            tags.add('коллокативный')

    # 6. Обработка составных ассоциаций
    assoc_wc = row.get('assoc_word_count', 1)
    auto_has_syn_comp = ('синтаксический' in auto_tags) and ('составная' in auto_tags)

    if assoc_wc == 1:
        if 'составная' in tags:
            tags.discard('составная')
            if auto_has_syn_comp:
                tags.discard('синтаксический')
                tags.discard('синтагматический')
                tags.add('синтаксический')
                tags.add('составная')

    # 7. Добавление из авто-разметки пропущенные формальные, эпидигматические, грамматические, идентичные связи
    for cls in ['формальный', 'эпидигматический', 'грамматический', 'идентичные']:
        if cls in auto_tags and cls not in tags:
            tags.add(cls)

    # 8. Парадигматика из авто-размтеки (только при POS_match == 1)
    if 'парадигматический' in auto_tags and 'парадигматический' not in tags and pos_match == 1:
        tags.add('парадигматический')

    # 9. Если итоговый список пуст, используем авто-метки
    if not tags:
        if auto_tags:
            tags = set(auto_tags)
        else:
            return 'не определена'

    # Сортировка
    priority_order = {
        'синтаксический': 0, 'синтагматический': 1, 'коллокативный': 2,
        'тематический': 3, 'парадигматический': 4, 'эпидигматический': 5,
        'формальный': 6, 'грамматический': 7, 'идентичные': 8, 'составная': 9
    }
    sorted_tags = sorted(tags, key=lambda t: priority_order.get(t, 99))
    return ' / '.join(sorted_tags)

# Применяем постобработку к каждой строке
df['тип связи_гибрид'] = df.apply(hybrid_label, axis=1)

# Сохранение финального результата
df_combined.to_excel(FINAL_OUTPUT, index=False)