# -*- coding: utf-8 -*-
"""2_network_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qswfInLiaOqCY2NGI0KIxv9Zo62olrsM

## Сетевой анализ ##

Строится однодольная проекция двудольного графа. Узлами будут стимулы. Ребра - общие ассоциации.
"""

import pandas as pd
import numpy as np
import networkx as nx
import math
import matplotlib.pyplot as plt
from networkx.algorithms.community import greedy_modularity_communities

df2= pd.read_csv('1_base_list.csv')

shared_lemmas = pd.read_csv('5_shared_lemmas.csv')

stimulus_N = df2.groupby('стимул')['частота'].sum().to_dict()
freq_map = df2.set_index(['стимул', 'лемма'])['частота'].to_dict()

G2 = nx.Graph()

# пересечения из shared_lemmas
for _, row in shared_lemmas.iterrows():
    lemma = row['лемма']
    stims = [s.strip() for s in str(row['список стимулов']).split(',')]

    # без слишком общих лемм
    if len(stims) > 15:
        continue

    for i in range(len(stims)):
        for j in range(i + 1, len(stims)):
            s1, s2 = stims[i], stims[j]

            # частоты
            f_ap = freq_map.get((s1, lemma), 0)
            f_bp = freq_map.get((s2, lemma), 0)
            min_freq = min(f_ap, f_bp)

            if min_freq > 0:
                if G2.has_edge(s1, s2):
                    G2[s1][s2]['sum_min'] += min_freq
                else:
                    G2.add_edge(s1, s2, sum_min=min_freq)

# расчет коэффициента Диза
for u, v, d in list(G2.edges(data=True)):
    Nu = stimulus_N.get(u)
    Nv = stimulus_N.get(v)

    if Nu and Nv:
        denominator = math.sqrt((2 * Nu) * (2 * Nv))
        G2[u][v]['weight'] = d['sum_min'] / denominator
    else:
        G2[u][v]['weight'] = 0

G2.remove_edges_from([(u, v) for u, v, d in G2.edges(data=True) if d.get('weight', 0) == 0])

print(f"Узлов: {G2.number_of_nodes()}, Ребер: {G2.number_of_edges()}")

#фильтрация
threshold_k = 0.016
G_final = G2.copy()
G_final.remove_edges_from([(u, v) for u, v, d in G_final.edges(data=True) if d.get('weight', 0) < threshold_k])
G_final.remove_nodes_from(list(nx.isolates(G_final)))

print(f"После фильтрации осталось: {G_final.number_of_nodes()} узлов и {G_final.number_of_edges()} ребер.")

edge_data = []
for u, v, d in G_final.edges(data=True):
    edge_data.append({
        'Стимул 1': u,
        'Стимул 2': v,
        'Коэффициент Диза': round(d['weight'], 4),
        'Сумма миним. частот': d['sum_min']
    })

df_top_edges = pd.DataFrame(edge_data).sort_values('Коэффициент Диза', ascending=False)

print("ТОП-20 самых сильных ассоциативных связей по Дизу:")
display(df_top_edges.head(20).style.hide(axis='index'))

centrality_degree = nx.degree_centrality(G_final)
centrality_betweenness = nx.betweenness_centrality(G_final, weight='weight')
centrality_closeness = nx.closeness_centrality(G_final)

df_graph_metrics = pd.DataFrame({
    'стимул': list(G_final.nodes()),
    'количество связей': [d for n, d in G_final.degree()],
    'взвешенная степень': [d for n, d in G_final.degree(weight='weight')],
    'центральность по степени': [centrality_degree[node] for node in G_final.nodes()],
    'степень посредничества': [centrality_betweenness[node] for node in G_final.nodes()],
    'степень близости': [centrality_closeness[node] for node in G_final.nodes()]
}).sort_values('количество связей', ascending=False)

display(df_graph_metrics.head(20))

communities = list(nx.community.greedy_modularity_communities(G_final))

fig = plt.figure(figsize=(40, 30))
pos = {}
rng = np.random.default_rng(seed=42)
group_centers = {i: rng.uniform(-15, 15, size=2) for i in range(len(communities))}

for i, comm in enumerate(communities):
    subgraph = G_final.subgraph(comm)
    local_pos = nx.spring_layout(subgraph, k=3.0, iterations=200, seed=42)
    for node in comm:
        pos[node] = local_pos[node] + group_centers[i]

# ребра (слабые и сильные)
nx.draw_networkx_edges(G_final, pos, width=1.5, alpha=0.4, edge_color='#999999')

strong_edges = [(u, v) for u, v, d in G_final.edges(data=True) if d['weight'] > 0.045]
nx.draw_networkx_edges(G_final, pos, edgelist=strong_edges, width=5.0, alpha=0.7, edge_color='steelblue')

# узлы
# важные узлы поверх остальных
sorted_nodes = sorted(G_final.nodes(), key=lambda n: centrality_degree[n])

for node in sorted_nodes:
    x, y = pos[node]
    # размер шрифта зависит от центральности
    font_sz = 12 + (centrality_degree[node] * 180)

    plt.text(x, y, s=node,
             fontsize=min(font_sz, 26),
             fontweight='bold',
             ha='center', va='center',
             bbox=dict(facecolor='white', alpha=0.7, edgecolor='none', pad=0.3))

plt.axis('off')
plt.title(f"Сеть ассоциативных связей стимулов (K >= {threshold_k})", fontsize=40, pad=20)


fig.savefig('graph_final.png', dpi=300, bbox_inches='tight')
fig.savefig('graph_final.pdf', bbox_inches='tight')

plt.show()

# Сохранение модели графа
nx.write_graphml(G_final, "associative_network.graphml")

# функция для поиска по графу общих лемм-ассоциаций для двух стимулов
def general_lemmas(stim1, stim2, shared_df):

    # по shared_df ищем строки, где оба стимула указаны в списке
    mask = shared_df['список стимулов'].apply(lambda x: stim1 in x and stim2 in x)
    common_lemmas = shared_df[mask].copy()

    if common_lemmas.empty:
        print(f"Общих лемм между '{stim1}' and '{stim2}' в этой таблице не найдено.")
        return

    print(f"Семантический мост: между {stim1} и {stim2}")
    print(f"Всего общих лемм-ассоциаций: {len(common_lemmas)}")

    print("\nОбщие ассоциации:")
    print(", ".join(common_lemmas['лемма'].tolist()))


general_lemmas('папа', 'мама', shared_lemmas)

# топ-5 групп
for i, comm in enumerate(communities[:5], 1):
    print(f"Группа {i} ({len(comm)} слов):")
    print(", ".join(sorted(list(comm))))

df_graph_metrics.to_csv('7_graph_metrics.csv', index=False, encoding='utf-8-sig')
