# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TW-ARWKLfhZ4IszpUENNA4eQ-jmohsvn
"""

# tools/graph_tools.py
# Функции для поиска по графу ассоциативных связей.

import networkx as nx
import pandas as pd
import os


# ----------------------------------------------------------------
# Функции загрузки данных
# ----------------------------------------------------------------

def load_graph(path: str = "data/associative_network.graphml") -> nx.Graph:
    """
    Загружает граф в формате GraphML.
    При отсутствии файла проверяет путь на уровень выше.
    """
    if not os.path.exists(path):
        alt_path = os.path.join("..", path)
        if os.path.exists(alt_path):
            path = alt_path
        else:
            raise FileNotFoundError(f"Файл не найден: {path}")
    return nx.read_graphml(path)


def load_shared_lemmas(path: str = "data/5_shared_lemmas.csv") -> pd.DataFrame:
    """
    Загружает датафрейм с пересекающимися леммами.
    При отсутствии файла проверяет путь на уровень выше.
    """
    if not os.path.exists(path):
        alt_path = os.path.join("..", path)
        if os.path.exists(alt_path):
            path = alt_path
        else:
            raise FileNotFoundError(f"Файл не найден: {path}")
    return pd.read_csv(path)


# ----------------------------------------------------------------
# Семантический мост между двумя стимулами
# ----------------------------------------------------------------

def general_lemmas(
    stim1: str,
    stim2: str,
    shared_df: pd.DataFrame,
) -> None:
    """
    Выводит общие леммы-ассоциации для двух стимулов (семантический мост).

    Параметры
    ----------
    stim1, stim2 : str
        Интересующие стимулы.
    shared_df : pd.DataFrame
        Датафрейм, полученный функцией load_shared_lemmas().
    """
    mask = shared_df['список стимулов'].apply(
        lambda x: stim1 in str(x) and stim2 in str(x)
    )
    common = shared_df[mask].copy()

    if common.empty:
        print(f"Общих лемм между '{stim1}' и '{stim2}' не найдено.")
        return

    print(f"Семантический мост: между {stim1} и {stim2}")
    print(f"Всего общих лемм-ассоциаций: {len(common)}")
    print("Общие ассоциации:\n" + ", ".join(common['лемма'].tolist()))


# ----------------------------------------------------------------
# Ближайшие соседи стимула в графе
# ----------------------------------------------------------------

def nearest_neighbors(
    G: nx.Graph,
    stimulus: str,
    top_n: int = 10,
) -> None:
    """
    Выводит top_n ближайших стимулов по весу ребра (формула Диза).
    """
    if stimulus not in G.nodes:
        print(f"Стимул '{stimulus}' отсутствует в графе.")
        return

    neighbors = sorted(
        G[stimulus].items(),
        key=lambda item: item[1].get('weight', 0),
        reverse=True,
    )[:top_n]

    print(f"Ближайшие соседи для '{stimulus}':")
    for nbr, data in neighbors:
        print(f"  {nbr}  (вес: {data.get('weight', 0):.3f})")


# ----------------------------------------------------------------
# Информация об узле
# ----------------------------------------------------------------

def node_info(G: nx.Graph, node: str) -> None:
    """Выводит степень и центральность для заданного узла."""
    if node not in G.nodes:
        print(f"Узел '{node}' не найден.")
        return

    degree = G.degree(node)
    between = nx.betweenness_centrality(G).get(node, 0)
    close = nx.closeness_centrality(G).get(node, 0)

    print(f"Информация об узле '{node}':")
    print(f"  Степень: {degree}")
    print(f"  Центральность по посредничеству: {between:.4f}")
    print(f"  Центральность по близости:     {close:.4f}")
