# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TW-ARWKLfhZ4IszpUENNA4eQ-jmohsvn
"""

# tools/summary_stats.py
# Функции для работы со сводными датасетами: статистика стимулов и ядерные ассоциации.

import pandas as pd
import os
from typing import Optional


# ----------------------------------------------------------------
# Загрузка данных
# ----------------------------------------------------------------

def load_summary(path: str = "data/2_summary_stats.csv") -> pd.DataFrame:
    """
    Загружает сводную статистику по стимулам.
    При отсутствии файла проверяет путь на уровень выше.
    """
    if not os.path.exists(path):
        alt_path = os.path.join("..", path)
        if os.path.exists(alt_path):
            path = alt_path
        else:
            raise FileNotFoundError(f"Файл не найден: {path}")
    return pd.read_csv(path)


def load_strongest(path: str = "data/4_strongest_associations.csv") -> pd.DataFrame:
    """
    Загружает датафрейм с ядерными ассоциациями.
    При отсутствии файла проверяет путь на уровень выше.
    """
    if not os.path.exists(path):
        alt_path = os.path.join("..", path)
        if os.path.exists(alt_path):
            path = alt_path
        else:
            raise FileNotFoundError(f"Файл не найден: {path}")
    return pd.read_csv(path)


# ----------------------------------------------------------------
# ТОП-стимулов по выбранной метрике
# ----------------------------------------------------------------

def get_top_stimuli(
    df: pd.DataFrame,
    metric: str,
    n: int = 20,
    ascending: bool = False,
) -> pd.DataFrame:
    """
    Возвращает список стимулов, лидирующих по заданной метрике.

    Параметры
    ----------
    df : pd.DataFrame
        Сводная статистика стимулов (результат load_summary()).
    metric : str
        Название колонки, по которой ранжируем.
    n : int
        Сколько стимулов вернуть.
    ascending : bool
        True – вернуть стимулы с наименьшим значением (антилидеры).

    Возвращает
    -------
    pd.DataFrame с колонками ['стимул', metric, 'всего'].
    """
    top_df = df.sort_values(metric, ascending=ascending).head(n).copy()
    top_df.index = range(1, len(top_df) + 1)
    title = "лидеров" if not ascending else "антилидеров"
    print(f"ТОП-{n} {title} по показателю '{metric}':")
    cols = ['стимул', metric, 'всего']
    return top_df[[c for c in cols if c in top_df.columns]]


# ----------------------------------------------------------------
# Ядерные ассоциации для конкретного стимула
# ----------------------------------------------------------------

def get_strongest_for_stimulus(
    df_strong: pd.DataFrame,
    stimulus: str,
) -> Optional[pd.DataFrame]:
    """
    Возвращает ядерные ассоциации для заданного стимула.

    Параметры
    ----------
    df_strong : pd.DataFrame
        Датафрейм с ядерными связями (результат load_strongest()).
    stimulus : str
        Интересующий стимул.

    Возвращает
    -------
    pd.DataFrame или None, если стимул не найден.
    """
    res = df_strong[df_strong['стимул'] == stimulus].sort_values(
        'частота', ascending=False
    )
    if res.empty:
        print(f"Для стимула '{stimulus}' ядерных ассоциаций не найдено.")
        return None
    print(f"Ядерные связи для слова '{stimulus}':")
    return res


# ----------------------------------------------------------------
# Краткий отчёт по одному стимулу
# ----------------------------------------------------------------

def stimulus_report(
    stimulus: str,
    df_sum: pd.DataFrame,
    df_strong: pd.DataFrame,
) -> None:
    """
    Печатает сводный отчёт по стимулу:
    общая статистика + ядерные ассоциации.

    Параметры
    ----------
    stimulus : str
        Стимул для отчёта.
    df_sum : pd.DataFrame
        Сводная статистика стимулов.
    df_strong : pd.DataFrame
        Ядерные ассоциации.
    """
    stats = df_sum[df_sum['стимул'] == stimulus]
    if stats.empty:
        print(f"Стимул '{stimulus}' не найден.")
        return

    row = stats.iloc[0]
    print(f"--- Отчёт по стимулу: {stimulus.upper()} ---")
    print(f"Всего реакций: {row.get('всего', '—')}")
    print(f"Различных ассоциаций: {row.get('различные ассоциации', '—')}")
    ttr = row.get('лексическое разнообразие', None)
    if ttr is not None:
        print(f"Лексическое разнообразие (TTR): {ttr:.3f}")
    print(f"Одиночных реакций: {row.get('одиночные ассоциации', '—')}")

    print("\nЯдерные ассоциации:")
    nuclear = df_strong[df_strong['стимул'] == stimulus].sort_values(
        'частота', ascending=False
    )
    if not nuclear.empty:
        for _, r in nuclear.iterrows():
            pct = r.get('сила связи %', None)
            pct_str = f" ({pct:.1f}%)" if pct is not None else ""
            print(f"  - {r['ассоциация']}{pct_str}")
    else:
        print("  Ядро не сформировано.")